server:
  port: 8080
spring:
  application:
    name: stock-predictor
  mvc:
    problemdetails:
      enabled: true
  cache:
    cache-names: [symbols, models]
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2

management:
  endpoints:
    web:
      exposure:
        include: [health, info, metrics]

marketdata:
  provider: alphaVantage # or finage
  alphaVantage:
    baseUrl: https://www.alphavantage.co
    apiKey:  SGG4XXWCBDO0KSCZ
  finage:
    baseUrl: https://api.finage.co.uk
    apiKey: ${FINAGE_API_KEY:}

